version: 2

project_name: smartsh

builds:
  - id: smartsh
    main: ./cmd/smartsh
    binary: smartsh
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
  - id: smartshd
    main: ./cmd/smartshd
    binary: smartshd
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: smartsh
    builds:
      - smartsh
      - smartshd
    name_template: "smartsh_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: BegaDeveloper
    name: smartsh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

